# ########## App Name ##########
spring.application.name=springboot-mariadb-library-project

# ########## Database connection ##########
spring.datasource.url=jdbc:mariadb://192.168.1.110:3306/library_db
spring.datasource.username=jonasMDB
spring.datasource.password=gn;6us5<j2:Rc!MH
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# ########## JPA/Hibernate setup ##########
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.jpa.properties.hibernate.format_sql=true